name: Test
on:
  push:
    branches:
      - master
permissions:
  contents: read
jobs:
  run-tests:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-22.04 ]
    steps:
      - name: Prepare Repository
        run: |
          cd /home/runner/work/superglue
          rm -rf superglue
          git clone https://github.com/imaginate/superglue.git
          cd superglue
          sudo make install
      - name: Run Tests
        run: make test
