name: Test
on:
  push:
    branches:
      - master
permissions:
  contents: read
jobs:
  run-tests:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-22.04 ]
    steps:
      - name: Run Tests
        run: make test
